//
// AuthStatusResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuthStatusResponse: Codable, JSONEncodable, Hashable {

    /** Authentication status */
    public var isAuthenticated: Bool

    public init(isAuthenticated: Bool) {
        self.isAuthenticated = isAuthenticated
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isAuthenticated = "is_authenticated"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isAuthenticated, forKey: .isAuthenticated)
    }
}

