//
// BusinessAddress.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Serializer for BusinessAddress model. Used for merchant and shipping addresses. */
public struct BusinessAddress: Codable, JSONEncodable, Hashable {

    public static let postalCodeRule = StringRule(minLength: nil, maxLength: 10, pattern: nil)
    public static let cityNameRule = StringRule(minLength: nil, maxLength: 32, pattern: nil)
    public static let stateNameRule = StringRule(minLength: nil, maxLength: 32, pattern: nil)
    public static let districtIdRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 2147483647, exclusiveMaximum: false, multipleOf: nil)
    public static let districtNameRule = StringRule(minLength: nil, maxLength: 32, pattern: nil)
    public static let longitudeRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^-?\\d{0,6}(?:\\.\\d{0,16})?$/")
    public static let latitudeRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^-?\\d{0,6}(?:\\.\\d{0,16})?$/")
    public static let buildingNumberRule = StringRule(minLength: nil, maxLength: 10, pattern: nil)
    public static let unitRule = StringRule(minLength: nil, maxLength: 50, pattern: nil)
    public static let receiverNameRule = StringRule(minLength: nil, maxLength: 100, pattern: nil)
    public static let receiverPhoneRule = StringRule(minLength: nil, maxLength: 100, pattern: nil)
    public var id: Int
    public var address: String
    public var postalCode: String?
    public var cityName: String
    public var stateName: String
    public var districtId: Int?
    public var districtName: String?
    public var longitude: Decimal?
    public var latitude: Decimal?
    public var buildingNumber: String?
    public var unit: String?
    public var receiverName: String?
    public var receiverPhone: String?
    public var isAccurate: Bool?
    public var isActive: Bool?
    public var createdAt: Date
    public var modifiedAt: Date

    public init(id: Int, address: String, postalCode: String? = nil, cityName: String, stateName: String, districtId: Int? = nil, districtName: String? = nil, longitude: Decimal? = nil, latitude: Decimal? = nil, buildingNumber: String? = nil, unit: String? = nil, receiverName: String? = nil, receiverPhone: String? = nil, isAccurate: Bool? = nil, isActive: Bool? = nil, createdAt: Date, modifiedAt: Date) {
        self.id = id
        self.address = address
        self.postalCode = postalCode
        self.cityName = cityName
        self.stateName = stateName
        self.districtId = districtId
        self.districtName = districtName
        self.longitude = longitude
        self.latitude = latitude
        self.buildingNumber = buildingNumber
        self.unit = unit
        self.receiverName = receiverName
        self.receiverPhone = receiverPhone
        self.isAccurate = isAccurate
        self.isActive = isActive
        self.createdAt = createdAt
        self.modifiedAt = modifiedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case address
        case postalCode = "postal_code"
        case cityName = "city_name"
        case stateName = "state_name"
        case districtId = "district_id"
        case districtName = "district_name"
        case longitude
        case latitude
        case buildingNumber = "building_number"
        case unit
        case receiverName = "receiver_name"
        case receiverPhone = "receiver_phone"
        case isAccurate = "is_accurate"
        case isActive = "is_active"
        case createdAt = "created_at"
        case modifiedAt = "modified_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(address, forKey: .address)
        try container.encodeIfPresent(postalCode, forKey: .postalCode)
        try container.encode(cityName, forKey: .cityName)
        try container.encode(stateName, forKey: .stateName)
        try container.encodeIfPresent(districtId, forKey: .districtId)
        try container.encodeIfPresent(districtName, forKey: .districtName)
        try container.encodeIfPresent(longitude, forKey: .longitude)
        try container.encodeIfPresent(latitude, forKey: .latitude)
        try container.encodeIfPresent(buildingNumber, forKey: .buildingNumber)
        try container.encodeIfPresent(unit, forKey: .unit)
        try container.encodeIfPresent(receiverName, forKey: .receiverName)
        try container.encodeIfPresent(receiverPhone, forKey: .receiverPhone)
        try container.encodeIfPresent(isAccurate, forKey: .isAccurate)
        try container.encodeIfPresent(isActive, forKey: .isActive)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(modifiedAt, forKey: .modifiedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension BusinessAddress: Identifiable {}
