//
// DeliveryTimeRangeDisplay.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DeliveryTimeRangeDisplay: Codable, JSONEncodable, Hashable {

    public var minDate: String
    public var maxDate: String

    public init(minDate: String, maxDate: String) {
        self.minDate = minDate
        self.maxDate = maxDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case minDate = "min_date"
        case maxDate = "max_date"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(minDate, forKey: .minDate)
        try container.encode(maxDate, forKey: .maxDate)
    }
}

