//
// ErrorEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** * &#x60;User is not authenticated.&#x60; - User is not authenticated. * &#x60;Order not found.&#x60; - نشان یافت نشد * &#x60;Order is not in a state where shipping can be selected.&#x60; - Order is not in a state where shipping can be selected. * &#x60;Order is not in a state where packing can be selected.&#x60; - Order is not in a state where packing can be selected. * &#x60;Failed to initiate refund. Please try again later.&#x60; - Failed to initiate refund. Please try again later. * &#x60;Order is expired or cancelled.&#x60; - Order is expired or cancelled. * &#x60;Invalid request origin.&#x60; - مبدأ نامعتبر * &#x60;Digi Express shipping method not found.&#x60; - مرسوله دیجی اکسپرس برای سفارش %s یافت نشد. * &#x60;Order address not found.&#x60; - نشان یافت نشد * &#x60;Failed to fetch Digi Express shipping time window options.&#x60; - خطا در ثبت مرسوله دیجی اکسپرس برای سفارش %s. دلیل: %s * &#x60;Address ID not found.&#x60; - نشان یافت نشد * &#x60;Failed to cancel shipment.&#x60; - Failed to cancel shipment. * &#x60;Failed to cancel shipment in third party service.&#x60; - Failed to cancel shipment in third party service. * &#x60;Shipment not found.&#x60; - نشان یافت نشد * &#x60;Selected shipping method is not eligible for cancellation.&#x60; - آیا روش ارسال پرداخت در مقصد است * &#x60;DigiExpress shipment is not in cancelable in this state&#x60; - مرسوله دیجی اکسپرس برای سفارش %s یافت نشد. * &#x60;DigiExpress shipment is not in reviveable in this state&#x60; - مرسوله دیجی اکسپرس برای سفارش %s یافت نشد. * &#x60;Failed to revive shipment in third party service.&#x60; - Failed to revive shipment in third party service. * &#x60;Selected shipping method is not eligible for revival.&#x60; - شناسه روش ارسال برای استفاده در سفارش */
public enum ErrorEnum: String, Codable, CaseIterable {
    case userIsNotAuthenticatedPeriod = "User is not authenticated."
    case orderNotFoundPeriod = "Order not found."
    case orderIsNotInAStateWhereShippingCanBeSelectedPeriod = "Order is not in a state where shipping can be selected."
    case orderIsNotInAStateWherePackingCanBeSelectedPeriod = "Order is not in a state where packing can be selected."
    case failedToInitiateRefundPeriodPleaseTryAgainLaterPeriod = "Failed to initiate refund. Please try again later."
    case orderIsExpiredOrCancelledPeriod = "Order is expired or cancelled."
    case invalidRequestOriginPeriod = "Invalid request origin."
    case digiExpressShippingMethodNotFoundPeriod = "Digi Express shipping method not found."
    case orderAddressNotFoundPeriod = "Order address not found."
    case failedToFetchDigiExpressShippingTimeWindowOptionsPeriod = "Failed to fetch Digi Express shipping time window options."
    case addressIdNotFoundPeriod = "Address ID not found."
    case failedToCancelShipmentPeriod = "Failed to cancel shipment."
    case failedToCancelShipmentInThirdPartyServicePeriod = "Failed to cancel shipment in third party service."
    case shipmentNotFoundPeriod = "Shipment not found."
    case selectedShippingMethodIsNotEligibleForCancellationPeriod = "Selected shipping method is not eligible for cancellation."
    case digiexpressShipmentIsNotInCancelableInThisState = "DigiExpress shipment is not in cancelable in this state"
    case digiexpressShipmentIsNotInReviveableInThisState = "DigiExpress shipment is not in reviveable in this state"
    case failedToReviveShipmentInThirdPartyServicePeriod = "Failed to revive shipment in third party service."
    case selectedShippingMethodIsNotEligibleForRevivalPeriod = "Selected shipping method is not eligible for revival."
}
