//
// GatewayTypeEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** * &#x60;1&#x60; - آنلاین * &#x60;2&#x60; - BNPL (الان بخر، بعداً پرداخت کن) * &#x60;3&#x60; - اعتباری * &#x60;4&#x60; - کیف پول دیجی‌پی * &#x60;5&#x60; - اقساط پیش‌فرض */
public enum GatewayTypeEnum: Int, Codable, CaseIterable {
    case _1 = 1
    case _2 = 2
    case _3 = 3
    case _4 = 4
    case _5 = 5
}
