//
// MerchantOrderCancelShipmentResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MerchantOrderCancelShipmentResponse: Codable, JSONEncodable, Hashable {

    /** Success message */
    public var message: String
    /** Order unique identifier */
    public var orderUuid: UUID
    /** Current order status  * `1` - اولیه * `2` - شروع شده * `3` - در انتظار * `4` - در انتظار درگاه * `5` - منقضی شده * `6` - لغو شده * `7` - پرداخت‌شده توسط کاربر * `8` - پرداخت موفیت آمیز نبود * `9` - تأیید شده توسط فروشگاه * `10` - تأیید توسط فروشگاه ناموفق بود * `11` - ناموفق از سوی فروشگاه * `12` - لغوشده توسط فروشگاه * `13` - درخواست بازگشت وجه به مشتری به دلیل درخواست مشتری * `14` - درخواست بازگشت وجه به فروشگاه پس از عدم تأیید توسط فروشگاه * `15` - درخواست بازگشت وجه به مشتری پس از ناموفق بودن توسط فروشگاه * `16` - بازپرداخت به فروشگاه پس از لغو توسط فروشگاه * `17` - بازپرداخت تکمیل شد * `18` - زمان انقضا گذشته است * `19` - تحویل شده * `20` - جمع اوری شده و در حال ارسال */
    public var status: OrderStatusEnum
    /** Human-readable status */
    public var statusDisplay: String

    public init(message: String, orderUuid: UUID, status: OrderStatusEnum, statusDisplay: String) {
        self.message = message
        self.orderUuid = orderUuid
        self.status = status
        self.statusDisplay = statusDisplay
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case orderUuid = "order_uuid"
        case status
        case statusDisplay = "status_display"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(message, forKey: .message)
        try container.encode(orderUuid, forKey: .orderUuid)
        try container.encode(status, forKey: .status)
        try container.encode(statusDisplay, forKey: .statusDisplay)
    }
}

