//
// MerchantOrderRefundResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MerchantOrderRefundResponse: Codable, JSONEncodable, Hashable {

    public var message: String
    public var orderUuid: UUID
    public var status: OrderStatusEnum
    public var statusDisplay: String
    public var refundReason: String

    public init(message: String, orderUuid: UUID, status: OrderStatusEnum, statusDisplay: String, refundReason: String) {
        self.message = message
        self.orderUuid = orderUuid
        self.status = status
        self.statusDisplay = statusDisplay
        self.refundReason = refundReason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case orderUuid = "order_uuid"
        case status
        case statusDisplay = "status_display"
        case refundReason = "refund_reason"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(message, forKey: .message)
        try container.encode(orderUuid, forKey: .orderUuid)
        try container.encode(status, forKey: .status)
        try container.encode(statusDisplay, forKey: .statusDisplay)
        try container.encode(refundReason, forKey: .refundReason)
    }
}

