//
// Merchant.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Merchant: Codable, JSONEncodable, Hashable {

    public static let nameRule = StringRule(minLength: nil, maxLength: 128, pattern: nil)
    public static let domainRule = StringRule(minLength: nil, maxLength: 200, pattern: nil)
    public var name: String?
    public var domain: String
    public var logo: String

    public init(name: String? = nil, domain: String, logo: String) {
        self.name = name
        self.domain = domain
        self.logo = logo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case domain
        case logo
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encode(domain, forKey: .domain)
        try container.encode(logo, forKey: .logo)
    }
}

