//
// MerchantPaidOrderList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Serializer for manager view listing PAID_BY_USER orders */
public struct MerchantPaidOrderList: Codable, JSONEncodable, Hashable {

    public var orderUuid: UUID
    /** شناسه منحصر به فرد سفارش در سیستم فروشنده */
    public var merchantOrderId: String
    /** شناسه منحصر به فرد برای پذیرنده برای تأیید سفارش */
    public var merchantUniqueId: String
    public var paidAt: Date?
    public var refundsAt: Date?

    public init(orderUuid: UUID, merchantOrderId: String, merchantUniqueId: String, paidAt: Date?, refundsAt: Date?) {
        self.orderUuid = orderUuid
        self.merchantOrderId = merchantOrderId
        self.merchantUniqueId = merchantUniqueId
        self.paidAt = paidAt
        self.refundsAt = refundsAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case orderUuid = "order_uuid"
        case merchantOrderId = "merchant_order_id"
        case merchantUniqueId = "merchant_unique_id"
        case paidAt = "paid_at"
        case refundsAt = "refunds_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(orderUuid, forKey: .orderUuid)
        try container.encode(merchantOrderId, forKey: .merchantOrderId)
        try container.encode(merchantUniqueId, forKey: .merchantUniqueId)
        try container.encode(paidAt, forKey: .paidAt)
        try container.encode(refundsAt, forKey: .refundsAt)
    }
}

