//
// MerchantOrderReviveShipmentResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MerchantOrderReviveShipmentResponse: Codable, JSONEncodable, Hashable {

    /** پیام موفق‌‌ */
    public var message: String
    /** شناسه منحصر به فرد سفارش */
    public var orderUuid: UUID
    /** وضعیت فعلی سفارش  * `1` - اولیه * `2` - شروع در * `3` - در انتظار * `4` - در انتظار درگاه * `5` - منقضی شده * `6` - لغو شده * `7` - ممنوع شده توسط ما * `8` - ناموفق در پرداخت * `9` - تأیید شده توسط فروشنده * `10` - ناموفق در تأیید توسط فروشنده * `11` - فروشگاه * `12` - لغو شده توسط فروشنده * `13` - درخواست بازگرداندن وجه به مشتری به دلیل درخواست مشتری * `14` - درخواست بازگرداندن وجه به فروشنده پس از ناموفقی در تأیید توسط فروشنده * `15` - درخواست بازگرداندن وجه به مشتری پس از ناموفقی توسط فروشنده * `16` - بازگردانده شده به فروشنده پس از لغو توسط فروشنده * `17` - بازگرداندن وجه تکمیل شد * `18` - زمان مجاز برای منقضی کردن گذشته است * `19` - تحویل نشده * `20` - مرسوله */
    public var status: OrderStatusEnum
    /** وضعیت قابل‌خواندن */
    public var statusDisplay: String

    public init(message: String, orderUuid: UUID, status: OrderStatusEnum, statusDisplay: String) {
        self.message = message
        self.orderUuid = orderUuid
        self.status = status
        self.statusDisplay = statusDisplay
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case orderUuid = "order_uuid"
        case status
        case statusDisplay = "status_display"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(message, forKey: .message)
        try container.encode(orderUuid, forKey: .orderUuid)
        try container.encode(status, forKey: .status)
        try container.encode(statusDisplay, forKey: .statusDisplay)
    }
}

