//
// Option.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Option: Codable, JSONEncodable, Hashable {

    /** نوع ویژگی محصول: رنگ، سایز، گارانتی، وزن یا سایر  * `color` - رنگ * `size` - اندازه * `warranty` - گارانتی * `weight` - وزن * `other` - سایر */
    public var typeName: TypeNameEnum
    /** نام ویژگی (مثلاً 'قرمز' برای رنگ قرمز، 'XL' برای سایز) */
    public var name: String
    /** مقدار ویژگی (مثلاً '#FF0000' برای کد رنگ یا مقدار دیگر) */
    public var value: String
    /** اگر نوع ویژگی رنگ است درست است، وگرنه غلط */
    public var isColor: Bool? = false

    public init(typeName: TypeNameEnum, name: String, value: String, isColor: Bool? = false) {
        self.typeName = typeName
        self.name = name
        self.value = value
        self.isColor = isColor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case typeName = "type_name"
        case name
        case value
        case isColor = "is_color"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(typeName, forKey: .typeName)
        try container.encode(name, forKey: .name)
        try container.encode(value, forKey: .value)
        try container.encodeIfPresent(isColor, forKey: .isColor)
    }
}

