//
// OrderCreateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrderCreateResponse: Codable, JSONEncodable, Hashable {

    public var orderStartUrl: String
    public var orderUuid: UUID

    public init(orderStartUrl: String, orderUuid: UUID) {
        self.orderStartUrl = orderStartUrl
        self.orderUuid = orderUuid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case orderStartUrl = "order_start_url"
        case orderUuid = "order_uuid"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(orderStartUrl, forKey: .orderStartUrl)
        try container.encode(orderUuid, forKey: .orderUuid)
    }
}

