//
// OrderDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrderDetail: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var createdAt: Date
    public var orderUuid: UUID
    /** Unix timestamp تا زمانی که سفارش برای پرداخت رزرو شده است */
    public var reservationExpiredAt: Int?
    /** شناسه منحصر به فرد سفارش در سیستم فروشنده */
    public var merchantOrderId: String
    public var status: OrderStatusEnum
    public var statusDisplay: String
    /** مجموع قیمت‌های اولیه تمام کالاها بدون تخفیف (به تومان) */
    public var mainAmount: Int
    /** قیمت نهایی قابل پرداخت توسط مشتری: مبلغ_اصلی - مبلغ_تخفیف + مبلغ_مالیات (به تومان) */
    public var finalAmount: Int
    /** مبلغ کل پرداخت شده توسط کاربر: مبلغ_نهایی + هزینه_ارسال (به تومان) */
    public var totalPaidAmount: Int
    /** کل تخفیف اعمال شده بر سفارش (به تومان) */
    public var discountAmount: Int
    /** مبلغ کل مالیات برای سفارش (به تومان) */
    public var taxAmount: Int
    /** هزینه ارسال برای سفارش (به تومان) */
    public var shippingAmount: Int
    /** مقدار تخفیف از برنامه باشگاه مشتریان/پاداش (به تومان) */
    public var loyaltyAmount: Int
    /** آدرسی برای دریافت اطلاع رسانی وضعیت پرداخت پس از تکمیل سفارش */
    public var callbackUrl: String
    public var merchant: Merchant
    public var items: [OrderItemCreate]
    public var sourceAddress: AnyCodable?
    public var destinationAddress: AnyCodable?
    public var selectedShippingMethod: ShippingMethod
    public var shippingSelectedAt: Date?
    public var addressSelectedAt: Date?
    /** هزینه روش بسته‌بندی انتخاب‌شده (به تومان) */
    public var packingAmount: Int
    public var packingSelectedAt: Date?
    public var selectedPacking: Packing
    public var canSelectPacking: Bool
    public var canSelectShipping: Bool
    public var canSelectAddress: Bool
    public var canProceedToPayment: Bool
    public var isPaid: Bool
    public var user: OrderUser
    public var payment: PaymentOrder
    /** زمان آمادهسازی سفارش (به روز) */
    public var preparationTime: Int
    /** وزن کل سفارش (بر حسب گرم) */
    public var weight: Double
    public var selectedShippingData: [String: AnyCodable]
    /** کد مرجع منحصر به فرد برای پیگیری سفارش مشتری (فرمت: BD-XXXXXXXX) */
    public var referenceCode: String
    public var promotionDiscountAmount: Double
    public var promotionData: [String: AnyCodable]
    /** مبلغ نشانه‌گذاری برای سفارش (به تومان) */
    public var digipayMarkupAmount: Int
    /** درصد کمیسیون نشانه‌گذاری برای سفارش (به درصد) */
    public var markupCommissionPercentage: Int
    public var previousStatus: OrderStatusEnum?
    public var previousStatusDisplay: String

    public init(id: Int, createdAt: Date, orderUuid: UUID, reservationExpiredAt: Int?, merchantOrderId: String, status: OrderStatusEnum, statusDisplay: String, mainAmount: Int, finalAmount: Int, totalPaidAmount: Int, discountAmount: Int, taxAmount: Int, shippingAmount: Int, loyaltyAmount: Int, callbackUrl: String, merchant: Merchant, items: [OrderItemCreate], sourceAddress: AnyCodable?, destinationAddress: AnyCodable?, selectedShippingMethod: ShippingMethod, shippingSelectedAt: Date?, addressSelectedAt: Date?, packingAmount: Int, packingSelectedAt: Date?, selectedPacking: Packing, canSelectPacking: Bool, canSelectShipping: Bool, canSelectAddress: Bool, canProceedToPayment: Bool, isPaid: Bool, user: OrderUser, payment: PaymentOrder, preparationTime: Int, weight: Double, selectedShippingData: [String: AnyCodable], referenceCode: String, promotionDiscountAmount: Double, promotionData: [String: AnyCodable], digipayMarkupAmount: Int, markupCommissionPercentage: Int, previousStatus: OrderStatusEnum?, previousStatusDisplay: String) {
        self.id = id
        self.createdAt = createdAt
        self.orderUuid = orderUuid
        self.reservationExpiredAt = reservationExpiredAt
        self.merchantOrderId = merchantOrderId
        self.status = status
        self.statusDisplay = statusDisplay
        self.mainAmount = mainAmount
        self.finalAmount = finalAmount
        self.totalPaidAmount = totalPaidAmount
        self.discountAmount = discountAmount
        self.taxAmount = taxAmount
        self.shippingAmount = shippingAmount
        self.loyaltyAmount = loyaltyAmount
        self.callbackUrl = callbackUrl
        self.merchant = merchant
        self.items = items
        self.sourceAddress = sourceAddress
        self.destinationAddress = destinationAddress
        self.selectedShippingMethod = selectedShippingMethod
        self.shippingSelectedAt = shippingSelectedAt
        self.addressSelectedAt = addressSelectedAt
        self.packingAmount = packingAmount
        self.packingSelectedAt = packingSelectedAt
        self.selectedPacking = selectedPacking
        self.canSelectPacking = canSelectPacking
        self.canSelectShipping = canSelectShipping
        self.canSelectAddress = canSelectAddress
        self.canProceedToPayment = canProceedToPayment
        self.isPaid = isPaid
        self.user = user
        self.payment = payment
        self.preparationTime = preparationTime
        self.weight = weight
        self.selectedShippingData = selectedShippingData
        self.referenceCode = referenceCode
        self.promotionDiscountAmount = promotionDiscountAmount
        self.promotionData = promotionData
        self.digipayMarkupAmount = digipayMarkupAmount
        self.markupCommissionPercentage = markupCommissionPercentage
        self.previousStatus = previousStatus
        self.previousStatusDisplay = previousStatusDisplay
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case createdAt = "created_at"
        case orderUuid = "order_uuid"
        case reservationExpiredAt = "reservation_expired_at"
        case merchantOrderId = "merchant_order_id"
        case status
        case statusDisplay = "status_display"
        case mainAmount = "main_amount"
        case finalAmount = "final_amount"
        case totalPaidAmount = "total_paid_amount"
        case discountAmount = "discount_amount"
        case taxAmount = "tax_amount"
        case shippingAmount = "shipping_amount"
        case loyaltyAmount = "loyalty_amount"
        case callbackUrl = "callback_url"
        case merchant
        case items
        case sourceAddress = "source_address"
        case destinationAddress = "destination_address"
        case selectedShippingMethod = "selected_shipping_method"
        case shippingSelectedAt = "shipping_selected_at"
        case addressSelectedAt = "address_selected_at"
        case packingAmount = "packing_amount"
        case packingSelectedAt = "packing_selected_at"
        case selectedPacking = "selected_packing"
        case canSelectPacking = "can_select_packing"
        case canSelectShipping = "can_select_shipping"
        case canSelectAddress = "can_select_address"
        case canProceedToPayment = "can_proceed_to_payment"
        case isPaid = "is_paid"
        case user
        case payment
        case preparationTime = "preparation_time"
        case weight
        case selectedShippingData = "selected_shipping_data"
        case referenceCode = "reference_code"
        case promotionDiscountAmount = "promotion_discount_amount"
        case promotionData = "promotion_data"
        case digipayMarkupAmount = "digipay_markup_amount"
        case markupCommissionPercentage = "markup_commission_percentage"
        case previousStatus = "previous_status"
        case previousStatusDisplay = "previous_status_display"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(orderUuid, forKey: .orderUuid)
        try container.encode(reservationExpiredAt, forKey: .reservationExpiredAt)
        try container.encode(merchantOrderId, forKey: .merchantOrderId)
        try container.encode(status, forKey: .status)
        try container.encode(statusDisplay, forKey: .statusDisplay)
        try container.encode(mainAmount, forKey: .mainAmount)
        try container.encode(finalAmount, forKey: .finalAmount)
        try container.encode(totalPaidAmount, forKey: .totalPaidAmount)
        try container.encode(discountAmount, forKey: .discountAmount)
        try container.encode(taxAmount, forKey: .taxAmount)
        try container.encode(shippingAmount, forKey: .shippingAmount)
        try container.encode(loyaltyAmount, forKey: .loyaltyAmount)
        try container.encode(callbackUrl, forKey: .callbackUrl)
        try container.encode(merchant, forKey: .merchant)
        try container.encode(items, forKey: .items)
        try container.encode(sourceAddress, forKey: .sourceAddress)
        try container.encode(destinationAddress, forKey: .destinationAddress)
        try container.encode(selectedShippingMethod, forKey: .selectedShippingMethod)
        try container.encode(shippingSelectedAt, forKey: .shippingSelectedAt)
        try container.encode(addressSelectedAt, forKey: .addressSelectedAt)
        try container.encode(packingAmount, forKey: .packingAmount)
        try container.encode(packingSelectedAt, forKey: .packingSelectedAt)
        try container.encode(selectedPacking, forKey: .selectedPacking)
        try container.encode(canSelectPacking, forKey: .canSelectPacking)
        try container.encode(canSelectShipping, forKey: .canSelectShipping)
        try container.encode(canSelectAddress, forKey: .canSelectAddress)
        try container.encode(canProceedToPayment, forKey: .canProceedToPayment)
        try container.encode(isPaid, forKey: .isPaid)
        try container.encode(user, forKey: .user)
        try container.encode(payment, forKey: .payment)
        try container.encode(preparationTime, forKey: .preparationTime)
        try container.encode(weight, forKey: .weight)
        try container.encode(selectedShippingData, forKey: .selectedShippingData)
        try container.encode(referenceCode, forKey: .referenceCode)
        try container.encode(promotionDiscountAmount, forKey: .promotionDiscountAmount)
        try container.encode(promotionData, forKey: .promotionData)
        try container.encode(digipayMarkupAmount, forKey: .digipayMarkupAmount)
        try container.encode(markupCommissionPercentage, forKey: .markupCommissionPercentage)
        try container.encode(previousStatus, forKey: .previousStatus)
        try container.encode(previousStatusDisplay, forKey: .previousStatusDisplay)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension OrderDetail: Identifiable {}
