//
// OrderItemCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrderItemCreate: Codable, JSONEncodable, Hashable {

    public static let nameRule = StringRule(minLength: nil, maxLength: 128, pattern: nil)
    public static let primaryAmountRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 2147483647, exclusiveMaximum: false, multipleOf: nil)
    public static let amountRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 2147483647, exclusiveMaximum: false, multipleOf: nil)
    public static let countRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 32767, exclusiveMaximum: false, multipleOf: nil)
    public static let discountAmountRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 2147483647, exclusiveMaximum: false, multipleOf: nil)
    public static let taxAmountRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 2147483647, exclusiveMaximum: false, multipleOf: nil)
    public static let imageLinkRule = StringRule(minLength: nil, maxLength: 500, pattern: nil)
    public static let preparationTimeRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let weightRule = NumericRule<Double>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** نام کامل محصول شامل تمام مشخصات */
    public var name: String
    /** قیمت اولیه برای هر واحد بدون تخفیف (به تومان) */
    public var primaryAmount: Int?
    /** قیمت نهایی برای تمام واحدها بعد از تخفیف (به تومان) */
    public var amount: Int?
    /** تعداد واحدهای این کالا در سفارش */
    public var count: Int
    /** مبلغ کل تخفیف برای این کالا (به تومان) */
    public var discountAmount: Int?
    /** مبلغ کل مالیات برای این کالا (به تومان) */
    public var taxAmount: Int?
    /** آدرس تصویر محصول */
    public var imageLink: String?
    public var options: [Option]
    /** Preparation time for the item (in days) */
    public var preparationTime: Int? = 2
    /** Weight of the item (in grams) */
    public var weight: Double?

    public init(name: String, primaryAmount: Int? = nil, amount: Int? = nil, count: Int, discountAmount: Int? = nil, taxAmount: Int? = nil, imageLink: String? = nil, options: [Option], preparationTime: Int? = 2, weight: Double? = nil) {
        self.name = name
        self.primaryAmount = primaryAmount
        self.amount = amount
        self.count = count
        self.discountAmount = discountAmount
        self.taxAmount = taxAmount
        self.imageLink = imageLink
        self.options = options
        self.preparationTime = preparationTime
        self.weight = weight
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case primaryAmount = "primary_amount"
        case amount
        case count
        case discountAmount = "discount_amount"
        case taxAmount = "tax_amount"
        case imageLink = "image_link"
        case options
        case preparationTime = "preparation_time"
        case weight
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(primaryAmount, forKey: .primaryAmount)
        try container.encodeIfPresent(amount, forKey: .amount)
        try container.encode(count, forKey: .count)
        try container.encodeIfPresent(discountAmount, forKey: .discountAmount)
        try container.encodeIfPresent(taxAmount, forKey: .taxAmount)
        try container.encodeIfPresent(imageLink, forKey: .imageLink)
        try container.encode(options, forKey: .options)
        try container.encodeIfPresent(preparationTime, forKey: .preparationTime)
        try container.encodeIfPresent(weight, forKey: .weight)
    }
}

