//
// OrderUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrderUser: Codable, JSONEncodable, Hashable {

    public static let firstNameRule = StringRule(minLength: nil, maxLength: 150, pattern: nil)
    public static let lastNameRule = StringRule(minLength: nil, maxLength: 150, pattern: nil)
    public static let phoneNumberRule = StringRule(minLength: nil, maxLength: 128, pattern: nil)
    public static let nationalIdentityNumberRule = StringRule(minLength: nil, maxLength: 10, pattern: nil)
    public var firstName: String?
    public var lastName: String?
    public var phoneNumber: String?
    public var nationalIdentityNumber: String?
    public var birthDate: Date?

    public init(firstName: String? = nil, lastName: String? = nil, phoneNumber: String? = nil, nationalIdentityNumber: String? = nil, birthDate: Date? = nil) {
        self.firstName = firstName
        self.lastName = lastName
        self.phoneNumber = phoneNumber
        self.nationalIdentityNumber = nationalIdentityNumber
        self.birthDate = birthDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case firstName = "first_name"
        case lastName = "last_name"
        case phoneNumber = "phone_number"
        case nationalIdentityNumber = "national_identity_number"
        case birthDate = "birth_date"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(firstName, forKey: .firstName)
        try container.encodeIfPresent(lastName, forKey: .lastName)
        try container.encodeIfPresent(phoneNumber, forKey: .phoneNumber)
        try container.encodeIfPresent(nationalIdentityNumber, forKey: .nationalIdentityNumber)
        try container.encodeIfPresent(birthDate, forKey: .birthDate)
    }
}

