//
// OrderCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrderCreate: Codable, JSONEncodable, Hashable {

    public static let merchantOrderIdRule = StringRule(minLength: nil, maxLength: 64, pattern: nil)
    public static let merchantUniqueIdRule = StringRule(minLength: nil, maxLength: 64, pattern: nil)
    public static let mainAmountRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 2147483647, exclusiveMaximum: false, multipleOf: nil)
    public static let finalAmountRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 2147483647, exclusiveMaximum: false, multipleOf: nil)
    public static let totalPaidAmountRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 2147483647, exclusiveMaximum: false, multipleOf: nil)
    public static let discountAmountRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 2147483647, exclusiveMaximum: false, multipleOf: nil)
    public static let taxAmountRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 2147483647, exclusiveMaximum: false, multipleOf: nil)
    public static let shippingAmountRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 2147483647, exclusiveMaximum: false, multipleOf: nil)
    public static let loyaltyAmountRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 2147483647, exclusiveMaximum: false, multipleOf: nil)
    public static let callbackUrlRule = StringRule(minLength: nil, maxLength: 256, pattern: nil)
    public static let reservationExpiredAtRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 2147483647, exclusiveMaximum: false, multipleOf: nil)
    public static let preparationTimeRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let weightRule = NumericRule<Double>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** شناسه منحصر به فرد این سفارش در سیستم فروشنده */
    public var merchantOrderId: String
    /** شناسه منحصر به فرد برای تأیید اصالت سفارش */
    public var merchantUniqueId: String
    /** مجموع قیمت‌های اولیه تمام کالاها بدون تخفیف (به تومان) */
    public var mainAmount: Int?
    /** مبلغ نهایی: مبلغ_اصلی - مبلغ_تخفیف + مبلغ_مالیات (به تومان) */
    public var finalAmount: Int?
    /** مبلغ کل پرداخت شده توسط کاربر: مبلغ_نهایی + هزینه_ارسال (به تومان) */
    public var totalPaidAmount: Int?
    /** مبلغ کل تخفیف برای تمام سفارش (به تومان) */
    public var discountAmount: Int?
    /** مبلغ کل مالیات برای تمام سفارش (به تومان) */
    public var taxAmount: Int?
    /** هزینه ارسال برای سفارش (به تومان) */
    public var shippingAmount: Int?
    /** مبلغ تخفیف باشگاه مشتریان/پاداش (به تومان) */
    public var loyaltyAmount: Int?
    /** آدرس وب‌هوک برای دریافت اطلاع رسانی وضعیت پرداخت */
    public var callbackUrl: String
    public var destinationAddress: AnyCodable?
    public var items: [OrderItemCreate]
    /** مقدار توسط سیستم جایگذاری می شود */
    public var merchant: Int?
    /** مقدار توسط سیستم جایگذاری می شود */
    public var sourceAddress: AnyCodable?
    public var user: Int?
    /** مهلت پرداخت (به عنوان Unix timestamp) قبل از اتمام سفارش */
    public var reservationExpiredAt: Int?
    /** کد مرجع منحصر به فرد برای پیگیری سفارش مشتری (فرمت: BD-XXXXXXXX) */
    public var referenceCode: String
    /** زمان آمادهسازی سفارش (به روز) */
    public var preparationTime: Int? = 2
    /** وزن کل سفارش (بر حسب گرم) */
    public var weight: Double?

    public init(merchantOrderId: String, merchantUniqueId: String, mainAmount: Int? = nil, finalAmount: Int? = nil, totalPaidAmount: Int? = nil, discountAmount: Int? = nil, taxAmount: Int? = nil, shippingAmount: Int? = nil, loyaltyAmount: Int? = nil, callbackUrl: String, destinationAddress: AnyCodable?, items: [OrderItemCreate], merchant: Int? = nil, sourceAddress: AnyCodable? = nil, user: Int?, reservationExpiredAt: Int? = nil, referenceCode: String, preparationTime: Int? = 2, weight: Double? = nil) {
        self.merchantOrderId = merchantOrderId
        self.merchantUniqueId = merchantUniqueId
        self.mainAmount = mainAmount
        self.finalAmount = finalAmount
        self.totalPaidAmount = totalPaidAmount
        self.discountAmount = discountAmount
        self.taxAmount = taxAmount
        self.shippingAmount = shippingAmount
        self.loyaltyAmount = loyaltyAmount
        self.callbackUrl = callbackUrl
        self.destinationAddress = destinationAddress
        self.items = items
        self.merchant = merchant
        self.sourceAddress = sourceAddress
        self.user = user
        self.reservationExpiredAt = reservationExpiredAt
        self.referenceCode = referenceCode
        self.preparationTime = preparationTime
        self.weight = weight
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case merchantOrderId = "merchant_order_id"
        case merchantUniqueId = "merchant_unique_id"
        case mainAmount = "main_amount"
        case finalAmount = "final_amount"
        case totalPaidAmount = "total_paid_amount"
        case discountAmount = "discount_amount"
        case taxAmount = "tax_amount"
        case shippingAmount = "shipping_amount"
        case loyaltyAmount = "loyalty_amount"
        case callbackUrl = "callback_url"
        case destinationAddress = "destination_address"
        case items
        case merchant
        case sourceAddress = "source_address"
        case user
        case reservationExpiredAt = "reservation_expired_at"
        case referenceCode = "reference_code"
        case preparationTime = "preparation_time"
        case weight
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(merchantOrderId, forKey: .merchantOrderId)
        try container.encode(merchantUniqueId, forKey: .merchantUniqueId)
        try container.encodeIfPresent(mainAmount, forKey: .mainAmount)
        try container.encodeIfPresent(finalAmount, forKey: .finalAmount)
        try container.encodeIfPresent(totalPaidAmount, forKey: .totalPaidAmount)
        try container.encodeIfPresent(discountAmount, forKey: .discountAmount)
        try container.encodeIfPresent(taxAmount, forKey: .taxAmount)
        try container.encodeIfPresent(shippingAmount, forKey: .shippingAmount)
        try container.encodeIfPresent(loyaltyAmount, forKey: .loyaltyAmount)
        try container.encode(callbackUrl, forKey: .callbackUrl)
        try container.encode(destinationAddress, forKey: .destinationAddress)
        try container.encode(items, forKey: .items)
        try container.encodeIfPresent(merchant, forKey: .merchant)
        try container.encodeIfPresent(sourceAddress, forKey: .sourceAddress)
        try container.encode(user, forKey: .user)
        try container.encodeIfPresent(reservationExpiredAt, forKey: .reservationExpiredAt)
        try container.encode(referenceCode, forKey: .referenceCode)
        try container.encodeIfPresent(preparationTime, forKey: .preparationTime)
        try container.encodeIfPresent(weight, forKey: .weight)
    }
}

