//
// Packing.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Packing: Codable, JSONEncodable, Hashable {

    public static let nameRule = StringRule(minLength: nil, maxLength: 64, pattern: nil)
    public static let priceRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 2147483647, exclusiveMaximum: false, multipleOf: nil)
    public var id: Int
    /** نام روش/گزینه بسته‌بندی */
    public var name: String
    /** هزینه بسته بندی به تومان */
    public var price: Int?

    public init(id: Int, name: String, price: Int? = nil) {
        self.id = id
        self.name = name
        self.price = price
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case price
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(price, forKey: .price)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Packing: Identifiable {}
