//
// PaymentOrder.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PaymentOrder: Codable, JSONEncodable, Hashable {

    public var finalAmount: Int
    public var gatewayType: GatewayTypeEnum
    public var gatewayTypeDisplay: String
    public var paidAt: String
    public var gatewayName: String?
    public var invoiceId: String?
    public var settlementDate: String
    public var settlementStatus: Int
    public var settlementStatusDisplay: String

    public init(finalAmount: Int, gatewayType: GatewayTypeEnum, gatewayTypeDisplay: String, paidAt: String, gatewayName: String?, invoiceId: String?, settlementDate: String, settlementStatus: Int, settlementStatusDisplay: String) {
        self.finalAmount = finalAmount
        self.gatewayType = gatewayType
        self.gatewayTypeDisplay = gatewayTypeDisplay
        self.paidAt = paidAt
        self.gatewayName = gatewayName
        self.invoiceId = invoiceId
        self.settlementDate = settlementDate
        self.settlementStatus = settlementStatus
        self.settlementStatusDisplay = settlementStatusDisplay
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case finalAmount = "final_amount"
        case gatewayType = "gateway_type"
        case gatewayTypeDisplay = "gateway_type_display"
        case paidAt = "paid_at"
        case gatewayName = "gateway_name"
        case invoiceId = "invoice_id"
        case settlementDate = "settlement_date"
        case settlementStatus = "settlement_status"
        case settlementStatusDisplay = "settlement_status_display"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(finalAmount, forKey: .finalAmount)
        try container.encode(gatewayType, forKey: .gatewayType)
        try container.encode(gatewayTypeDisplay, forKey: .gatewayTypeDisplay)
        try container.encode(paidAt, forKey: .paidAt)
        try container.encode(gatewayName, forKey: .gatewayName)
        try container.encode(invoiceId, forKey: .invoiceId)
        try container.encode(settlementDate, forKey: .settlementDate)
        try container.encode(settlementStatus, forKey: .settlementStatus)
        try container.encode(settlementStatusDisplay, forKey: .settlementStatusDisplay)
    }
}

