//
// RefundOrder.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Serializer for refunding an order. */
public struct RefundOrder: Codable, JSONEncodable, Hashable {

    public static let reasonRule = StringRule(minLength: nil, maxLength: 500, pattern: nil)
    /** دلیل اختیاری برای بازگرداندن وجه */
    public var reason: String?

    public init(reason: String? = nil) {
        self.reason = reason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case reason
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(reason, forKey: .reason)
    }
}

