//
// ReviveShipment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ReviveShipment: Codable, JSONEncodable, Hashable {

    public static let preparationTimeRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** زمان آمادهسازی سفارش (به روز) */
    public var preparationTime: Int?

    public init(preparationTime: Int? = nil) {
        self.preparationTime = preparationTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case preparationTime = "preparation_time"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(preparationTime, forKey: .preparationTime)
    }
}

