//
// ShippingTypeEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** * &#x60;1&#x60; - سایر * &#x60;2&#x60; - دیجی اکسپرس */
public enum ShippingTypeEnum: Int, Codable, CaseIterable {
    case _1 = 1
    case _2 = 2
}
