//
// ShippingMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Serializer for shipping method details. */
public struct ShippingMethod: Codable, JSONEncodable, Hashable {

    public static let nameRule = StringRule(minLength: nil, maxLength: 64, pattern: nil)
    public static let costRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 2147483647, exclusiveMaximum: false, multipleOf: nil)
    public static let secondaryCostRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 2147483647, exclusiveMaximum: false, multipleOf: nil)
    public static let minimumTimeSendingRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 32767, exclusiveMaximum: false, multipleOf: nil)
    public static let maximumTimeSendingRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 32767, exclusiveMaximum: false, multipleOf: nil)
    public var id: Int
    /** نام روش/گزینه بسته‌بندی */
    public var name: String
    /** شناسه روش ارسال برای استفاده در سفارش */
    public var description: String?
    /** شناسه وضعیت ارسال از دیجی اکسپرس  * `1` - سایر * `2` - دیجی اکسپرس */
    public var shippingType: ShippingTypeEnum?
    public var getShippingTypeDisplay: String
    public var shippingTypeDisplay: String
    /** هزینه ارسال برای منطقه اصلی (مثلاً تهران) به تومان */
    public var cost: Int?
    /** هزینه ارسال برای مناطق دیگر به تومان */
    public var secondaryCost: Int?
    /** حداقل تعداد روز از تاریخ سفارش تا تحویل */
    public var minimumTimeSending: Int?
    /** Maximum number of days from order date to delivery */
    public var maximumTimeSending: Int?
    public var deliveryTimeDisplay: String
    public var deliveryTimeRangeDisplay: DeliveryTimeRangeDisplay
    public var inventoryAddress: BusinessAddress
    /** آیا روش ارسال پرداخت در مقصد است */
    public var isPayAtDestination: Bool?

    public init(id: Int, name: String, description: String? = nil, shippingType: ShippingTypeEnum? = nil, getShippingTypeDisplay: String, shippingTypeDisplay: String, cost: Int? = nil, secondaryCost: Int? = nil, minimumTimeSending: Int? = nil, maximumTimeSending: Int? = nil, deliveryTimeDisplay: String, deliveryTimeRangeDisplay: DeliveryTimeRangeDisplay, inventoryAddress: BusinessAddress, isPayAtDestination: Bool? = nil) {
        self.id = id
        self.name = name
        self.description = description
        self.shippingType = shippingType
        self.getShippingTypeDisplay = getShippingTypeDisplay
        self.shippingTypeDisplay = shippingTypeDisplay
        self.cost = cost
        self.secondaryCost = secondaryCost
        self.minimumTimeSending = minimumTimeSending
        self.maximumTimeSending = maximumTimeSending
        self.deliveryTimeDisplay = deliveryTimeDisplay
        self.deliveryTimeRangeDisplay = deliveryTimeRangeDisplay
        self.inventoryAddress = inventoryAddress
        self.isPayAtDestination = isPayAtDestination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case description
        case shippingType = "shipping_type"
        case getShippingTypeDisplay = "get_shipping_type_display"
        case shippingTypeDisplay = "shipping_type_display"
        case cost
        case secondaryCost = "secondary_cost"
        case minimumTimeSending = "minimum_time_sending"
        case maximumTimeSending = "maximum_time_sending"
        case deliveryTimeDisplay = "delivery_time_display"
        case deliveryTimeRangeDisplay = "delivery_time_range_display"
        case inventoryAddress = "inventory_address"
        case isPayAtDestination = "is_pay_at_destination"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(shippingType, forKey: .shippingType)
        try container.encode(getShippingTypeDisplay, forKey: .getShippingTypeDisplay)
        try container.encode(shippingTypeDisplay, forKey: .shippingTypeDisplay)
        try container.encodeIfPresent(cost, forKey: .cost)
        try container.encodeIfPresent(secondaryCost, forKey: .secondaryCost)
        try container.encodeIfPresent(minimumTimeSending, forKey: .minimumTimeSending)
        try container.encodeIfPresent(maximumTimeSending, forKey: .maximumTimeSending)
        try container.encode(deliveryTimeDisplay, forKey: .deliveryTimeDisplay)
        try container.encode(deliveryTimeRangeDisplay, forKey: .deliveryTimeRangeDisplay)
        try container.encode(inventoryAddress, forKey: .inventoryAddress)
        try container.encodeIfPresent(isPayAtDestination, forKey: .isPayAtDestination)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ShippingMethod: Identifiable {}
