//
// TypeNameEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** * &#x60;color&#x60; - رنگ * &#x60;size&#x60; - اندازه * &#x60;warranty&#x60; - گارانتی * &#x60;weight&#x60; - وزن * &#x60;other&#x60; - سایر */
public enum TypeNameEnum: String, Codable, CaseIterable {
    case color = "color"
    case size = "size"
    case warranty = "warranty"
    case weight = "weight"
    case other = "other"
}
