//
// VerifyOrder.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VerifyOrder: Codable, JSONEncodable, Hashable {

    /** شناسه منحصر به فرد ارسال شده هنگام ساخت سفارش برای تأیید اصالت سفارش */
    public var merchantUniqueId: String

    public init(merchantUniqueId: String) {
        self.merchantUniqueId = merchantUniqueId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case merchantUniqueId = "merchant_unique_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(merchantUniqueId, forKey: .merchantUniqueId)
    }
}

