//
// WalletBalance.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WalletBalance: Codable, JSONEncodable, Hashable {

    public static let amountRule = NumericRule<Int>(minimum: -2147483648, exclusiveMinimum: false, maximum: 2147483647, exclusiveMaximum: false, multipleOf: nil)
    /** Current wallet balance in Tomans */
    public var amount: Int?
    /** Deadline for settling negative balance */
    public var negativeSettlementDeadline: String?

    public init(amount: Int? = nil, negativeSettlementDeadline: String?) {
        self.amount = amount
        self.negativeSettlementDeadline = negativeSettlementDeadline
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case negativeSettlementDeadline = "negative_settlement_deadline"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(amount, forKey: .amount)
        try container.encode(negativeSettlementDeadline, forKey: .negativeSettlementDeadline)
    }
}

