//
// OrderShippingAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class OrderShippingAPI {

    /**
     Cancel Shipment
     
     - parameter orderUuid: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func orderApiV1ManagerCancelShipmentCreate(orderUuid: UUID, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: MerchantOrderCancelShipmentResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return orderApiV1ManagerCancelShipmentCreateWithRequestBuilder(orderUuid: orderUuid).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Cancel Shipment
     - POST /order/api/v1/manager/{order_uuid}/cancel-shipment/
     - <div dir=\"rtl\" style=\"text-align: right;\">  لغو مرسوله دیجی‌اکسپرس  ## توضیحات  این endpoint برای لغو یک مرسوله ثبت‌شده در سرویس دیجی‌اکسپرس استفاده می‌شود. پس از لغو موفق، مرسوله از صف ارسال خارج می‌شود.  نیاز به **API_KEY** فروشنده دارد.  ## شرایط لغو  * سفارش باید دارای روش ارسال **DigiExpress** باشد * مرسوله باید در وضعیت **در انتظار تحویل به پیک** (Request for Pickup) باشد  </div>  ```mermaid sequenceDiagram     participant M as فروشنده     participant API as BWDK API     participant DX as دیجی‌اکسپرس      M->>API: POST /order/api/v1/manager/{order_uuid}/cancel-shipment/     Note over M,API: Header: X-API-KEY (بدون بدنه)      alt روش ارسال DigiExpress نیست         API-->>M: 400 خطا         Note over API,M: {error: \"Selected shipping method is not DigiExpress\"}     else مرسوله قابل لغو نیست         API-->>M: 400 خطا         Note over API,M: {error: \"...\"}     else لغو موفق         API->>DX: لغو مرسوله         DX-->>API: تأیید لغو         API-->>M: 200 موفق         Note over API,M: {message, order_uuid, status, status_display}     end ``` 
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: MerchantAPIKeyAuth
     - parameter orderUuid: (path)  
     - returns: RequestBuilder<MerchantOrderCancelShipmentResponse> 
     */
    open class func orderApiV1ManagerCancelShipmentCreateWithRequestBuilder(orderUuid: UUID) -> RequestBuilder<MerchantOrderCancelShipmentResponse> {
        var localVariablePath = "/order/api/v1/manager/{order_uuid}/cancel-shipment/"
        let orderUuidPreEscape = "\(APIHelper.mapValueToPathItem(orderUuid))"
        let orderUuidPostEscape = orderUuidPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{order_uuid}", with: orderUuidPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MerchantOrderCancelShipmentResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Change Shipping Method
     
     - parameter orderUuid: (path)  
     - parameter orderDetail: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func orderApiV1ManagerChangeShippingMethodUpdate(orderUuid: UUID, orderDetail: OrderDetail, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: OrderDetail?, _ error: Error?) -> Void)) -> RequestTask {
        return orderApiV1ManagerChangeShippingMethodUpdateWithRequestBuilder(orderUuid: orderUuid, orderDetail: orderDetail).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Change Shipping Method
     - PUT /order/api/v1/manager/{order_uuid}/change-shipping-method/
     - <div dir=\"rtl\" style=\"text-align: right;\">  تغییر روش ارسال سفارش  ## توضیحات  این endpoint به فروشنده اجازه می‌دهد روش ارسال یک سفارش را تغییر دهد. این عملیات معمولاً زمانی استفاده می‌شود که فروشنده بخواهد از DigiExpress به روش ارسال پیش‌فرض (یا بالعکس) تغییر دهد.  نیاز به **API_KEY** فروشنده دارد.  ## پارامترهای ورودی  * **updated_shipping**: شناسه روش ارسال جدید * **preparation_time** (اختیاری): زمان آماده‌سازی (روز) برای DigiExpress  </div> 
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: MerchantAPIKeyAuth
     - parameter orderUuid: (path)  
     - parameter orderDetail: (body)  
     - returns: RequestBuilder<OrderDetail> 
     */
    open class func orderApiV1ManagerChangeShippingMethodUpdateWithRequestBuilder(orderUuid: UUID, orderDetail: OrderDetail) -> RequestBuilder<OrderDetail> {
        var localVariablePath = "/order/api/v1/manager/{order_uuid}/change-shipping-method/"
        let orderUuidPreEscape = "\(APIHelper.mapValueToPathItem(orderUuid))"
        let orderUuidPostEscape = orderUuidPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{order_uuid}", with: orderUuidPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: orderDetail)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<OrderDetail>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Revive Shipment
     
     - parameter orderUuid: (path)  
     - parameter reviveShipment: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func orderApiV1ManagerReviveShipmentCreate(orderUuid: UUID, reviveShipment: ReviveShipment? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: MerchantOrderReviveShipmentResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return orderApiV1ManagerReviveShipmentCreateWithRequestBuilder(orderUuid: orderUuid, reviveShipment: reviveShipment).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Revive Shipment
     - POST /order/api/v1/manager/{order_uuid}/revive-shipment/
     - <div dir=\"rtl\" style=\"text-align: right;\">  احیای مرسوله دیجی‌اکسپرس  ## توضیحات  این endpoint برای احیای (reactivate) یک مرسوله دیجی‌اکسپرس که قبلاً لغو شده یا در وضعیت غیرفعال است استفاده می‌شود. با ارسال `preparation_time` (زمان آماده‌سازی بر حسب روز)، زمان جدید آماده بودن بار تنظیم می‌شود.  نیاز به **API_KEY** فروشنده دارد.  ## پارامترهای ورودی  * **preparation_time** (اختیاری، پیش‌فرض: ۲): تعداد روز تا آماده‌شدن بار برای تحویل به پیک  ## شرایط  * سفارش باید دارای روش ارسال **DigiExpress** باشد * مرسوله باید در وضعیت قابل احیا باشد  </div>  ```mermaid sequenceDiagram     participant M as فروشنده     participant API as BWDK API     participant DX as دیجی‌اکسپرس      M->>API: POST /order/api/v1/manager/{order_uuid}/revive-shipment/     Note over M,API: Header: X-API-KEY<br/>{preparation_time: 2}      alt روش ارسال DigiExpress نیست         API-->>M: 400 خطا         Note over API,M: {error: \"Selected shipping method is not DigiExpress\"}     else احیا موفق         API->>DX: احیای مرسوله با زمان جدید         DX-->>API: تأیید احیا         API-->>M: 200 موفق         Note over API,M: {message, order_uuid, status, status_display}     end ``` 
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: MerchantAPIKeyAuth
     - parameter orderUuid: (path)  
     - parameter reviveShipment: (body)  (optional)
     - returns: RequestBuilder<MerchantOrderReviveShipmentResponse> 
     */
    open class func orderApiV1ManagerReviveShipmentCreateWithRequestBuilder(orderUuid: UUID, reviveShipment: ReviveShipment? = nil) -> RequestBuilder<MerchantOrderReviveShipmentResponse> {
        var localVariablePath = "/order/api/v1/manager/{order_uuid}/revive-shipment/"
        let orderUuidPreEscape = "\(APIHelper.mapValueToPathItem(orderUuid))"
        let orderUuidPostEscape = orderUuidPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{order_uuid}", with: orderUuidPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: reviveShipment)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MerchantOrderReviveShipmentResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
